[package]
name = "btd6_autoplay"
authors = ["Cameron Maclean <BowsiePup@users.noreply.github.com>", "Mark Hutchison <MoonstarCoding@users.noreply.github.com>"]
version = "3.0.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
clap = { version = "4.5.21", features = ["derive"] }
device_query = "2.1.0"
enigo = "0.2.1"
fragile = "2.0.0"
image = "0.25.5"
inquire = "0.7.5"
lazy_static = "1.5.0"
regex = "1.11.1"
rusty-tesseract = "1.1.10"
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
struct_iterable = "0.1.1"
xcap = "0.0.14"
