start: ["space"]
pause: ["`"]
menu: ["escape"]
sell: ["backspace"]
upgrade_top_path: [","]
upgrade_middle_path: ["."]
upgrade_bottom_path: ["/"]
dart: ["q"]
boomerang: ["w"]
bomb: ["e"]
tack: ["r"]
ice: ["t"]
glue: ["y"]
sniper: ["z"]
sub: ["x"]
boat: ["c"]
ace: ["v"]
heli: ["b"]
mortar: ["n"]
dartling: ["m"]
wizard: ["a"]
super_monkey: ["s"]
ninja: ["d"]
alchemist: ["f"]
druid: ["g"]
farm: ["h"]
spike: ["j"]
village: ["k"]
engineer: ["l"]
beast: ["i"]
hero: ["u"]
target_priority_right: ["tab"]
target_priority_left: ["l_control", "tab"]
target_priority_special: ["page_down"]
send_next_round: ["shift", "space"]
road_spikes: ["shift", "1"]
moab_mine: ["shift", "2"]
glue_trap: ["shift", "3"]
camo_trap: ["shift", "4"]
banana_farmer: ["shift", "5"]
tech_bot: ["shift", "6"]
energizing_totem: ["shift", "7"]
pontoon: ["shift", "8"]
portable_lake: ["shift", "9"]
super_monkey_storm: ["shift", "0"]
monkey_boost: ["shift", "-"]
thrive: ["shift", "="]
time_stop: ["shift", "["]
cash_drop: ["shift", "]"]
copy: ["l_control", "c"]
