start: ["space"]
pause: ["`"]
menu: ["esc"]
sell: ["backspace"]
upgrade_top_path: [","]
upgrade_middle_path: ["."]
upgrade_bottom_path: ["/"]
dart: ["q"]
boomerang: ["w"]
bomb: ["e"]
tack: ["r"]
ice: ["t"]
glue: ["y"]
sniper: ["z"]
sub: ["x"]
boat: ["c"]
ace: ["v"]
heli: ["b"]
mortar: ["n"]
dartling: ["m"]
wizard: ["a"]
super_monkey: ["s"]
ninja: ["d"]
alchemist: ["f"]
druid: ["g"]
farm: ["h"]
spike: ["j"]
village: ["k"]
engineer: ["l"]
beast: ["i"]
hero: ["u"]
target_priority_right: ["tab"]
target_priority_left: ["tab", "ctrl"]
target_priority_special: ["pagedown"]
send_next_round: ["space", "shift"]
road_spikes: ["1", "shift"]
moab_mine: ["2", "shift"]
glue_trap: ["3", "shift"]
camo_trap: ["4", "shift"]
banana_farmer: ["5", "shift"]
tech_bot: ["6", "shift"]
energizing_totem: ["7", "shift"]
pontoon: ["8", "shift"]
portable_lake: ["9", "shift"]
super_monkey_storm: ["0", "shift"]
monkey_boost: ["-", "shift"]
thrive: ["=", "shift"]
time_stop: ["[", "shift"]
cash_drop: ["]", "shift"]
copy: ["c", "ctrl"]
