screen:
  x: 0
  y: 0
  w: 1920
  h: 1080
game:
  victoryBanner:
    x: 700
    y: 666
    w: 515
    h: 110
  defeatBanner:
    x: 590
    y: 584
    w: 730
    h: 115
  nextButton:
    x: 965
    y: 1464
  freeplayButton:
    x: 1220
    y: 629
  freeplayOkButton:
    x: 965
    y: 1309
  restartGameButton:
    x: 1080
    y: 1390
  confirmButton:
    x: 1135
    y: 1948
  homeButton:
    x: 845
    y: 1404
  roundCounter:
    x: 1841
    y: 47
    w: 244
    h: 44