screen:
  x: 0
  y: 0
  w: 2560
  h: 1140
game:
  victoryBanner:
    x: 782
    y: 107
    w: 1006
    h: 249
  defeatBanner:
    x: 590
    y: 584
    w: 730
    h: 115
  nextButton:
    x: 1281
    y: 1215
  freeplayButton:
    x: 1598
    y: 1129
  freeplayOkButton:
    x: 1279
    y: 1012
  restartGameButton:
    x: 1426
    y: 1121
  confirmButton:
    x: 1521
    y: 973
  roundCounter:
    x: 1835
    y: 38
    w: 246
    h: 64
