screen:
  x: 0
  y: 0
  w: 1440
  h: 1920
game:
  victoryBanner:
    x: 782
    y: 107
    w: 1006
    h: 249
  defeatBanner:
    x: 590
    y: 584
    w: 730
    h: 115
  nextButton:
    x: 1281
    y: 1215
  freeplayButton:
    x: 1598
    y: 1129
  freeplayOkButton:
    x: 1279
    y: 1012
  restartGameButton:
    x: 1426
    y: 1121
  confirmButton:
    x: 1521
    y: 973
  roundCounter:
    x: 1835
    y: 38
    w: 246
    h: 64
hotkeys:
  start: ["space"]
  pause: ["`"]
  menu: ["esc"]
  sell: ["backspace"]
  upgradeTopPath: [","]
  upgradeMiddlePath: ["."]
  upgradeBottomPath: ["/"]
  dart: ["q"]
  boomerang: ["w"]
  bomb: ["e"]
  tack: ["r"]
  ice: ["t"]
  glue: ["y"]
  sniper: ["z"]
  sub: ["x"]
  boat: ["c"]
  ace: ["v"]
  heli: ["b"]
  mortar: ["n"]
  dartling: ["m"]
  wizard: ["a"]
  super: ["s"]
  ninja: ["d"]
  alchemist: ["f"]
  druid: ["g"]
  farm: ["h"]
  spike: ["j"]
  village: ["k"]
  engineer: ["l"]
  beast: ["i"]
  hero: ["u"]
  targetPriorityRight: ["tab"]
  targetPriorityLeft: ["tab", "ctrl"]
  targetPrioritySpecial: "pagedown"
  sendNextRound: ["space", "shift"]
  roadSpikes: ["1", "shift"]
  moabMine: ["2", "shift"]
  glueTrap: ["3", "shift"]
  camoTrap: ["4", "shift"]
  bananaFarmer: ["5", "shift"]
  techBot: ["6", "shift"]
  energizingTotem: ["7", "shift"]
  pontoon: ["8", "shift"]
  portableLake: ["9", "shift"]
  superMonkeyStorm: ["0", "shift"]
  monkeyBoost: ["-", "shift"]
  thrive: ["=", "shift"]
  timeStop: ["[", "shift"]
  cashDrop: ["]", "shift"]
  copy: ["c", "ctrl"]
progressBar:
  prefix: "Progress: ["
  suffix: "] {0}%"
  completed: "#"
  null: "-"
